### ISSUE TITLE
Ошибка при использовании notification

### ISSUE THREAD

**Issue by dinamicus** [lasthead0/yandex2mqtt#5]
Если добавить блок в конфиг notification
module.exports = {
notification: [
    {
        skill_id: 'blabla',
        oauth_token: 'blabla',
        user_id: '2'
    },
]
    mqtt: {
        host: 'localhost',
        port: 1883,
        user: 'user',
        password: 'password',
    },

то y2m не запускается с ошибкой

 > yandex2mqtt@0.2.0 start
> node app.js

/opt/yandex2mqtt/config.js:9
    mqtt: {
    ^^^^

SyntaxError: Unexpected identifier
    at wrapSafe (internal/modules/cjs/loader.js:988:16)
    at Module._compile (internal/modules/cjs/loader.js:1036:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/opt/yandex2mqtt/app.js:22:16)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)

пометка на     at Object.<anonymous> (/opt/yandex2mqtt/app.js:22:16)

**Comment by lasthead0** [comment]
Тут явно не хватает запятой. Стоит начать с этого.
```
module.exports = {
  notification: [
    {
      skill_id: 'blabla',
      oauth_token: 'blabla',
      user_id: '2'
    },
  ],<-----
  mqtt: {
    host: 'localhost',
    port: 1883,
    user: 'user',
    password: 'password',
  },
  ...
}
```

**Comment by dinamicus** [comment]
Действительно. в описании отсутствует запятая. Спасибо, заработало!
