### ISSUE TITLE
Не видит датчики, ошибки

### ISSUE THREAD

**Issue by pmaster555** [lasthead0/yandex2mqtt#8]
> node app.js

TypeError: Cannot read property 'getState' of undefined
    at module.exports.query (/opt/yandex2mqtt/routes/user.js:61:44)
    at Layer.handle [as handle_request] (/opt/yandex2mqtt/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/yandex2mqtt/node_modules/express/lib/router/route.js:137:13)
    at complete (/opt/yandex2mqtt/node_modules/passport/lib/middleware/authenticate.js:268:13)
    at /opt/yandex2mqtt/node_modules/passport/lib/middleware/authenticate.js:275:15
    at pass (/opt/yandex2mqtt/node_modules/passport/lib/authenticator.js:431:14)
    at Authenticator.transformAuthInfo (/opt/yandex2mqtt/node_modules/passport/lib/authenticator.js:453:5)
    at /opt/yandex2mqtt/node_modules/passport/lib/middleware/authenticate.js:272:22
    at /opt/yandex2mqtt/node_modules/passport/lib/http/request.js:52:7
    at /opt/yandex2mqtt/node_modules/passport/lib/sessionmanager.js:26:5

при чем управление работает а данные от датчиков не идут ...

**Comment by lasthead0** [comment]
По данному stack trace я не могу понять причину ошибки, не могу её воспроизвести.
Могу предложить проверить конфиг, отвязать навык УД от y2m и привязать по новой.

**Comment by pmaster555** [comment]
Пробовал даже с пустым конфигом. удалил временно все устройства, оставил только данные авторизации. работает, какое то время проходит и такая ошибка ( пробовал оставить просто один датчик.

**Comment by pmaster555** [comment]
С датчиками разобрался. Ошибка не при чем. она не мешает, но иногда все равно появляется.
